config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  resources :messages, only: [:new, :create]
  resources :call_masters, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call_master.rb
class CallMaster
  include ActiveModel::Model

  attr_accessor :name, :phone, :breaking, :address

  PHONE_NUMBER = /\A\d{3}-\d{3}-\d{4}\z/
  validates :name, presence: true, length: { maximum: 20 }
  validates :phone, presence: true, numericality: true, length: { minimum: 7, maximum: 15 }
  validates :address, length: { maximum: 400 }
  validates :breaking, presence: true
end

app/models/message.rb
class Message
  include ActiveModel::Model
  # Attributes (DSL provided by Virtus)
  attr_accessor :name, :phone, :comment
  PHONE_NUMBER = /\A\d{3}-\d{3}-\d{4}\z/
  validates :name, presence: true, length: { maximum: 20 }
  validates :phone, presence: true, numericality: true, length: { minimum: 7, maximum: 15 }
  validates :comment, length: { maximum: 600 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/call_masters_controller.rb
class CallMastersController < ApplicationController
  def new
    @call_master = CallMaster.new
  end

  def create
    @message = Message.new
    @call_master = CallMaster.new(call_masters_params)
    if @call_master.valid?
      CallMastersMailer.call_masters_message(@call_master).deliver
      redirect_to root_path, notice: 'Спасибо! Мы Вам скоро перезвоним'
    else
      render 'static_pages/index'
    end
  end

  private

  def call_masters_params
    params.require(:call_master).permit(:name, :phone, :breaking, :address)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @call_master = CallMaster.new
    @message = Message.new(message_params)
    if @message.valid?
      MessagesMailer.callback_information(@message).deliver
      redirect_to root_path, notice: 'Спасибо! Мы Вам скоро перезвоним'
    else
      render 'static_pages/index'
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :phone, :comment)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @message = Message.new
    @call_master = CallMaster.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/call_masters_helper.rb
module CallMastersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/call_masters/_form.html.slim
.row.contact-form
  .secHeader
    h3.text-center
      | Вызов Мастера онлайн
  fieldset.col-md-12.col-sm-12
    = form_for @call_master, url: call_masters_path do |f|
      - if @call_master.errors.any?
          #error_explanation
            .alert.alert-error
              | Проблемы возникли со следующими полями
            ul
              - @call_master.errors.full_messages.each do |msg|
                li
                  | *** 
                  = msg
      = f.text_field :name, :placeholder => 'Имя'

      = f.text_field :phone, :placeholder => 'Телефон в формате 38095XXXXXXX'
       
      = f.text_field :breaking, :placeholder => 'Что сломалось?'
      
      = f.text_area :address, :placeholder => 'Укажите Ваш адресс для приезда мастера'

      = f.submit :Отправить, class:'btn btn-info'
      end
    end

app/views/call_masters/new.html.slim
= render 'form'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | PlatinumService
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link[href='http://fonts.googleapis.com/css?family=Raleway:400,100,600' rel='stylesheet' type='text/css']
    script[src="js/modernizr.custom.js"]
    = render 'shared/ie'
  body
    = render 'shared/header'
    = render 'shared/slider'
    = render 'shared/flash'
    = yield
    = render 'shared/services'
    = render 'shared/how_work'
    = render 'shared/about'
    = render 'shared/contact'
    = render 'shared/footer'
    
    script[src="js/jquery-1.10.2.min.js"]
    script $.fn.cycle.defaults.autoSelector = '.slideshow'
    script[src="js/jquery.cycle2.min.js"]
    script[src="js/jquery.cycle2.carousel.min.js"]
    script[src="js/jquery.cookie.js"]
    script[src="js/others.js"]
    script[src="js/jquery.nivo.slider.js"]
    script[src="js/lib/jquery.mousewheel-3.0.6.pack.js"]1
    




      

app/views/messages/_form.html.slim
.row.contact-form
  .secHeader
    h3.text-center
      | обратный вызов
  fieldset.col-md-12.col-sm-12
    = form_for @message, url: messages_path do |f|
      - if @message.errors.any?
          #error_explanation
            .alert.alert-error
              | Проблемы возникли со следующими полями
            ul
              - @message.errors.full_messages.each do |msg|
                li
                  | *** 
                  = msg
      = f.text_field :name, :placeholder => 'Имя'

      = f.text_field :phone, :placeholder => 'Телефон в формате 38095XXXXXXX'
       
      = f.text_area :comment, :placeholder => 'Комментарий'
      
      = f.submit :Отправить, class:'btn btn-info'
      end
    end

app/views/messages/new.html.slim
= render 'form'

app/views/shared/_about.html.slim
#templatemo_about.section3
  .container
    .row
      .col-md-12
        .secHeader
          h1.text-center
            | О нас
          p.text-center
            small
              b
               | Наша компания более 10 лет на рынке услуг. За плечами огромный опыт.
          p.text-center
            b
             | У нас высокое качество обслуживания по самым доступным ценам! Все наши клиенты имеют большое преимущество:
          br
        ul.services
          li
            h4
              b
                | Мы даем гарантию 1 год на замену деталей;
          li
            h4
              b
                | У нас индивидуальный подход к каждому клиенту;
          li
            h4
              b
                | Работаем круглосуточно в будни, выходные и праздничные дни;
          li
            h4
              b 
                | Мы даем гарантию 1 год на замену деталей;
          li
            h4
              b
                | При покупке б/у стиральной машины Вы получаете химическую чистку в подарок.
        br
        p[style="font-size:18px"]
          b
            | Если Вам необходимы услуги по ремонту стиральной машины или холодильника в Киеве или Киеской области, звоните уже сейчас! Для новых и постоянных клиентов действуют хорошие скидки!
        .secHeader
          h2.text-center[style="color:red"]
            | Расширение компании
          p.text-center
            b
              | В связи с расширением компании, в команду Platinum-Service производится набор высококвалифицированных мастеров по специальностям:
        ul.services
          li
            h4
              b
                | Мастер по ремонту стиральных и посудомоечных машин;
          li
            h4
              b
                | Мастер по ремонту холодильников;
          li
            h4
              b
                | Мастер по ремонту электроники (модулей управления стиральных машин, посудомоечных машин, холодильников);
          li
            h4
              b
                | Мастер-сантехник.
        .row
          .col-md-12
            .socials.sbot
              ul
                li
                  a[href="https://twitter.com"]
                    i.fa.fa-twitter.soc
                li
                  a[href="https://www.facebook.com"]
                    i.fa.fa-facebook.soc
                li
                  a[href="https://www.vk.com"]
                    i.fa.fa-vk.soc
                li
                  a[href="https://www.instagram.com"]
                    i.fa.fa-instagram.soc

app/views/shared/_contact.html.slim
#templatemo_contact.section5
  .container
    .row
      .col-md-12
        .secHeader
          h1.text-center
            | Наши контакты
    .row
      .col-md-6.col-md-offset-3.text-center.col-sm-12.col-xs-12
        .addr
          ul
            li
              i.fa.fa-map-marker
              | г.Киев, ул.Березняковская, д.27
            li
              i.fa.fa-mobile-phone
              | (068) 126-83-79
            li
              i.fa.fa-mobile-phone
              | (095) 636-86-75
            li
              i.fa.fa-mobile-phone
              | (063) 863-99-49
            li
              i.fa.fa-envelope
              | evgeniymozgovoy1234@gmail.com
            li
              i.fa.fa-envelope
              | info@kiev-servis.com.ua
    p.text-center
      b
        | Оставьте свои данные в этой форме и мы Вам обязательно перезвоним.
    .row
      .col-md-6.col-md-offset-3.col-lg-6.col-sm-6.col-sm-offset-3.col-xs-8.col-xs-offset-2
        = render 'messages/form'
    .row
      .col-md-6.col-md-offset-3.col-lg-6.col-sm-6.col-sm-offset-3.col-xs-8.col-xs-offset-2
        = render 'call_masters/form'
.opener.text-center
  span
    a#togg[href="#foo" onclick="toggle_visibility('foo');"]
      | Скрыть

app/views/shared/_flash.html.slim
.my-flash.row
  .col-md-4.col-md-offset-4
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"

app/views/shared/_footer.html.slim
footer#foo.footer
  .container
    .row
      .col-md-4
        .addr
          p
            span[style="color:#00BFFF"]
              | Platinum-Service 
            | дорожит своей репутацией и своими клиентами, поэтому мы предоставляем услуги на высшем уровне.
          p
            | Позвоните к нам! Наши мастера быстро и эффективно устранят поломку в любой точке Киева и Киевской области
      .col-md-4
        .logo
          = image_tag "/images/Logo.png", alt: 'Platinum-Service'
      .col-md-4
        p
          | Для наших клиентов действуют постоянные скидки!
            Не упустите возможности воспользоваться качественными услугами опытных мастеров!
    .row
      h3.text-center[style="color:#00BFFF"]
        | Наши контакты  
      ul.footer_contact.col-md-6.col-md-offset-3.text-center
        li
          i.fa.fa-map-marker
          |  г.Киев, ул.Березняковская, д.27
        li
          i.fa.fa-mobile-phone
          |  (068) 126-83-79
        li
          i.fa.fa-mobile-phone
          |  (095) 636-86-75
        li
          i.fa.fa-mobile-phone
          |  (063) 863-99-49
        li
          i.fa.fa-envelope
          | www.evgeniymozgovoy1234@gmail.com
        li
          i.fa.fa-envelope
          | info@kiev-servis.com.ua
      
#back-top.gotop.text-center
  a[href=""]
    | Вернуться вверх
.bfWrap.text-center
  .templatemo_footer
    | Copyright © 2017 Platinum-Service created by Sobolev Sergey

app/views/shared/_header.html.slim
header
  .mWrapper.navbar.navbar-fixed-top
    #templatemo_top
      .container
        .row
          .mainTop
            .hidden-xs.hidden-sm.col-md-6
              .mailme
                a[href="#"]
                  i.fa.fa-envelope
                  | info@kiev-servis.com.ua
            .col-sm-12.col-md-6
              .socials
                ul
                  li
                    a[href="https://twitter.com"]
                      i.fa.fa-twitter.soc
                  li
                    a[href="https://www.facebook.com"]
                      i.fa.fa-facebook.soc
                  li
                    a[href="https://www.vk.com"]
                      i.fa.fa-vk.soc
                  li
                    a[href="https://www.instagram.com"]
                      i.fa.fa-instagram.soc

          .col-sm-3.col-md-4.col-xs-5
            .logo
              a[href="#"]
                = image_tag "/images/Logo.png", alt: 'Platinum-Service'
          .col-sm-9.col-md-8.col-xs-7
            nav.mainMenu
              ul.nav
                li
                  a#up[href="#"]
                    | Наверх
                li
                  a[href="#templatemo_services"]
                    | Услуги и Цены
                li
                  a[href="#templatemo_portfolio"]
                    | Как мы работаем
                li
                  a[href="#templatemo_about"]
                    | О нас
                li
                  a[href="#templatemo_contact"]
                    | Контакты

app/views/shared/_how_work.html.slim
#templatemo_portfolio.section2
  .container
    .row
      .col-md-12
        .secHeader
          h1.text-center
            | Как мы работаем
          p.text-center
            | Наша схема работы очень проста и понятна. От обращения до ремонта техники происходит несколько этапов
    .row.text-center
      .col-md-4.col-sm-4.features
        i.fa.fa-phone.fa-4x
        p.title
          | Прием заявки
        p.text
          | Вы сообщаете адрес и описываете неисправность. Диспетчер проводит первичную диагностику, сообщает время визита мастера.
      .col-md-4.col-sm-4.features
        i.fa.fa-clock-o.fa-4x
        p.title
          | Выезд мастера
        p.text 
          | Мастер согласовывает с Вами время визита и точно в договренное время он прибудет. 
      .col-md-4.col-sm-4.features
        i.fa.fa-clock-o.fa-4x
        p.title
          | Диагностика
        p.text 
          | Мастер сообщает информацию о поломке, возможных причинах её возникновения, и способах ремонта.
    .row.text-center
      .col-md-4.col-sm-4.features
        i.fa.fa-calculator.fa-4x
        p.title
          | Расчет стоимости
        p.text 
          | После диагностики мастер сообщает вам окончательную стоимость ремонта, которая будет фигурировать в документах.
      .col-md-4.col-sm-4.features
        i.fa.fa-wrench.fa-4x
        p.title
          | Ремонт техники
        p.text 
          | Наши линейные автомобили укомплектованы внушительным запасом деталей. Среднее время ремонта от 45 минут до 2 часов.
      .col-md-4.col-sm-4.features
        i.fa.fa-pencil-square-o.fa-4x
        p.title
          | Гарантия
        p.text 
          | Гарантия на запчасти 3-6 месяцев. Гарантия на работу мастера по ремонту техники составляет от 6 до 12 месяцев.
    br
    br
    br
    .row
      .col-md-12
        .secHeader
          h2.text-center
            | Мы работаем со следующими 
            span[style="color:#00BFFF"]
             | марками 
      .col-md-10.col-md-offset-1
        = image_tag "/images/technika.png"

app/views/shared/_ie.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
<![endif]-->

app/views/shared/_services.html.slim
#templatemo_services.section1
  .container
    .row
      .col-md-12
        .secHeader
          h1.text-center
            | Наши услуги
          p.text-center[style="color:red"]
            b
              | АКЦИЯ!!! Всем нашим клиентам СКИДКИ на ремонт техники от 5%!
              br
              | Работаем круглосуточно!
                Звоните в любое удобное для Вас время!
        .row.service_image
          .ice.col-md-6.col-md-offset-3.col-sm-12.col-xs-12.col-md-offset-1
            = image_tag "/images/remont.png", alt: 'Ремонт холодильников, эдектропечей'
        br
        br
        h4.text-center
          b
            | Наша фирма производит следующиe виды ремонтных
            span[style="color:#00BFFF"]
             |  услуг
          br
        ul.services
          li.first
            h4.text-center
              b
               | Мастер по ремонту стиральных машин.
          .wash.col-md-3.col-md-offset-1.col-sm-6.col-xs-6.col-lg-6
            = image_tag "/images/wash_mashine.jpg", alt: 'Ремонт стиральных машин'
          li
            h4
              b
               | Мастер по ремонту холодильников.
          li
            h4
              b
               | Мастер по ремонту сушильных машин.
          li
            h4
              b
               | Мастер по ремонту посудомоечных машин, пароварок.
          .dish.col-md-2.col-sm-6.col-xs-6.col-lg-6
            = image_tag "/images/dish_mashine.png", alt: 'Ремонт посудомоечных машин'
          li
            h4
              b
               | Мастер по ремонту электроплит, электродуховок, микроволновок.
          li
            h4
              b
               | Мастер электрик.
          li
            h4
              b
               | Мастер сантехник.
          li
            h4[style="color:red"]
              b
               | Скупка Б/У стиральных машин
          li
            h4[style="color:red"]
              b
               | Продажа Б/У стиральных машин
        br
        br
        br
        h2.text-center
          | Цены
        ul.services
          li
            h4
              b
                | Стоимость вызова мастера для ремонта стиральной машины:
              ul
                li
                  p
                    b
                      | По Киеву 90 гривен
                li
                  p
                    b
                      | По Киевской области 90 гривен + 10 гривен за каждый километр
          li
            h4
              b
                | Стоимость вызова мастера для ремонта посудомоечной или сушильной машины:
              ul
                li
                  p
                    b
                      | по Киеву 200 гривен
                li
                  p
                    b
                      | по Киевской области 200 гривен + 10 гривен за каждый километр

            li 
              h4
                b
                  | Стоимость вызова мастера для ремонта холодильника:
                ul
                  li
                    p
                      b
                        | по Киеву 200 гривен
                  li
                    p
                      b
                        | по Киевской области 200 гривен + 10 гривен за каждый километр
            li
              h4
                b
                  | Минимальная работа мастера от 150 гривен
            li
              h4
                b 
                  | Каждый клиент получает гарантийный талон на проведенный комплекс работ
                    по ремонту стиральной машины. Срок действия талона 1 год.
            li
              h4
                b 
                  | Диагностика стиральной машины и консультации - бесплатно!
    .row.clean
      .col-md-12
        .secHeader
          h1.text-center
            | Клининговые услуги
        h4.text-center 
          b
            | Наша компания с удовольствием поможет Вам поддерживать ежедневную чистоту квартир, домов, офисов, кафе, ресторанов, складских помещений, гостиниц и других помещений. В нужные сроки с лучшим качеством!
        h4.text-center[style="color:red"]
          b
           | АКЦИЯ!!! Новым клиентам СКИДКИ на первую уборку 10%! Звоните сейчас!

        br
      ul.col-md-5.col-sm-7.services
        li
          h4
            b
             | Уборка квартир и частных домов.
        li
          h4
            b
             | Уборка административных помещений и офисов.
        li
          h4
            b
             | Уборка производственных помещений, складов.
        li
          h4
            b
             | Уборка отелей.
        li
          h4
            b
             | Уборка ресторанов, кафе.
        li
          h4
            b
             | Уборка торговых центров, супермаркетов.
        li
          h4
            b
             | Уборка после ремонта.
      .col-md-5.col-md-offset-2.col-sm-5.col-xs-12.text-center
        =image_tag "/images/clean1.png", alt: 'Уборка квартир, помещений'
        br
    .row.price
      .secHeader
        h2.text-center[style="color:#00BFFF"]
          | Цены на клининговые услуги
      ul
        li
          h2.text-center[style="color:red"]
            b
              | Привлекательные цены
        ul.services
          li
            h4
              b
                | Уборка кафе и ресторанов:

              ul
                li
                  p
                    b
                      | площадь от 40 до 80 м2 - от 1375 грн.
          li
            h4
              b
                | Уборка складских помещений:
                li
                  p
                    b
                      | площадь от 40 до 80 м2 - от 716 грн.:
          li
            h4
              b
                | Уборка гостиниц и хостелов:
                li
                  p
                    b
                      | площадь от 40 до 80 м2 - от 632 гривен
          li  
            p 
              b
                | Цены на большую площадь и другие услуги можно узнать позвонив по телефонам ниже.
        .row
          .col-md-6.col-md-offset-3.text-center.col-sm-12.col-xs-12
            .addr
              ul
                li
                  i.fa.fa-map-marker
                  | г.Киев, ул.Березняковская, д.27
                li
                  i.fa.fa-mobile-phone
                  | (068) 126-83-79
                li
                  i.fa.fa-mobile-phone
                  | (095) 636-86-75
                li
                  i.fa.fa-mobile-phone
                  | (095) 636-86-75
              li 
                h3[style="color:red"]
                  b
                    | Новым клиентам СКИДКИ на первую уборку 10%! Звоните сейчас!

app/views/shared/_slider.html.slim
.theme-default
  #slider.nivoSlider
    img[src="images/cleaning1.png" data-thumb="images/cleaning1.png" alt="Клининговые услуги" title="Наша компания занимается клининговыми услугами."]
    img[src="images/cleaning2.png" data-thumb="images/cleaning2.png" alt="Уборка, клининг, уборка любой сложности" title="Мы выполняем уборку любой сложности, а также любых помещений"]
    img[src="images/service1.png" data-thumb="images/service1.png" alt="Ремонт стиральных машин" title="Также мы предоставляем услуги по ремонту стиральных машин, электроплит"]
    img[src="images/service2.png" data-thumb="images/service2.png" alt="Ремонт холодильников, посудомоечных машин, электродуховок, а также любой техники" title="Ремонтируем холодильники, посудомоечные машины, пароварки, микровалновки и др."]